import type { StaffClassItem } from "@/types/staff"

export const mockStaffClasses: StaffClassItem[] = [
  {
    id: "mock-class-10293",
    code: "CLASS-10293",
    studentName: "Lê Trọng Tấn",
    tutorName: "Nguyễn Văn Bình",
    subject: "Toán học",
    location: "Quận 1, TP.HCM",
    feePerSession: "200.000",
    totalSessions: "24 buổi",
    status: "Đang học",
    startDate: "15/11/2023",
    endDate: "15/02/2024",
  },
  {
    id: "mock-class-10295",
    code: "CLASS-10295",
    studentName: "Trần Mỹ Duyên",
    tutorName: "Trần Thị Cẩm",
    subject: "Vật lý",
    location: "Quận 7, TP.HCM",
    feePerSession: "250.000",
    totalSessions: "20 buổi",
    status: "Hoàn thành",
    startDate: "01/10/2023",
    endDate: "20/12/2023",
  },
  {
    id: "mock-class-10297",
    code: "CLASS-10297",
    studentName: "Hoàng Gia Bảo",
    tutorName: "Phan Ngọc Hà",
    subject: "Hóa học",
    location: "Phú Nhuận, TP.HCM",
    feePerSession: "220.000",
    totalSessions: "18 buổi",
    status: "Tạm dừng",
    startDate: "22/11/2023",
    endDate: "22/01/2024",
  },
]
