import type { RequestItem, TutorRecommendation } from "@/types/class_request"
import type { StaffClassItem } from "@/types/staff"

export const requests: RequestItem[] = [
  {
    id: "#RQ-10293",
    rawId: "mock-rq-10293",
    createdAt: "12/10/2023",
    name: "Lê Trọng Tấn",
    role: "Phụ huynh",
    phone: "0901 234 567",
    subject: "Toán học",
    level: "Lớp 10",
    area: "Quận 1, TP.HCM",
    schedule: "Tối Thứ 2, Thứ 4 · 19:00 - 21:00",
    note: "Ưu tiên gia sư ĐH Bách Khoa hoặc KHTN, có kinh nghiệm dạy kèm cấp 3.",
    status: "Chờ xử lý",
  },
  {
    id: "#RQ-10294",
    rawId: "mock-rq-10294",
    createdAt: "13/10/2023",
    name: "Ngô Minh An",
    role: "Học viên",
    phone: "0935 451 882",
    subject: "Tiếng Anh",
    level: "IELTS Foundation",
    area: "Thủ Đức, TP.HCM",
    schedule: "Sáng Thứ 7, Chủ nhật · 08:00 - 10:00",
    note: "Cần gia sư thiện về phát âm, giao tiếp, có giáo trình nền tảng phù hợp cho học viên mới.",
    status: "Đang xử lý",
  },
  {
    id: "#RQ-10295",
    rawId: "mock-rq-10295",
    createdAt: "13/10/2023",
    name: "Trần Mỹ Duyên",
    role: "Phụ huynh",
    phone: "0918 877 520",
    subject: "Vật lý",
    level: "Lớp 11",
    area: "Quận 7, TP.HCM",
    schedule: "Chiều Thứ 3, Thứ 5 · 17:30 - 19:30",
    note: "Ưu tiên gia sư có kinh nghiệm luyện học sinh khá giỏi, bổ trợ thêm bài tập nâng cao.",
    status: "Đã ghép",
  },
  {
    id: "#RQ-10296",
    rawId: "mock-rq-10296",
    createdAt: "14/10/2023",
    name: "Phạm Hữu Đức",
    role: "Học viên",
    phone: "0982 612 008",
    subject: "Ngữ văn",
    level: "Lớp 9",
    area: "Bình Thạnh, TP.HCM",
    schedule: "Tối Thứ 6, Chủ nhật · 18:30 - 20:00",
    note: "Cần gia sư theo sát kỹ năng viết đoạn văn nghị luận và củng cố phần đọc hiểu.",
    status: "Đang xử lý",
  },
  {
    id: "#RQ-10297",
    rawId: "mock-rq-10297",
    createdAt: "15/10/2023",
    name: "Hoàng Gia Bảo",
    role: "Phụ huynh",
    phone: "0907 225 114",
    subject: "Hóa học",
    level: "Lớp 12",
    area: "Phú Nhuận, TP.HCM",
    schedule: "Tối Thứ 3, Thứ 6 · 19:30 - 21:00",
    note: "Tập trung ôn thi tốt nghiệp, cần gia sư có lộ trình bài tập rõ ràng theo tuần.",
    status: "Chờ xử lý",
  },
]

export const tutors: TutorRecommendation[] = [
  {
    id: "mock-tutor-1",
    rawTutorId: "mock-tutor-1",
    name: "Nguyễn Văn Bình",
    meta: "2 năm kinh nghiệm · Sinh viên ĐH Bách Khoa",
    match: "95% Match",
    avatar: "NV",
    tags: ["Toán", "Vật lý", "Quận 1, Quận 5", "Khớp 2/2 buổi"],
    status: "Hồ sơ đã duyệt",
    highlight: "bg-green-600",
  },
  {
    id: "mock-tutor-2",
    rawTutorId: "mock-tutor-2",
    name: "Trần Thị Cẩm",
    meta: "5 năm kinh nghiệm · Giáo viên THPT",
    match: "85% Match",
    avatar: "TC",
    tags: ["Toán", "Hóa học", "Quận 1, Quận 4, Quận 7", "Khớp 1/2 buổi"],
    status: "Hồ sơ đã duyệt",
    highlight: "bg-orange-500",
  },
  {
    id: "mock-tutor-3",
    rawTutorId: "mock-tutor-3",
    name: "Lê Minh Đạt",
    meta: "1.5 năm kinh nghiệm · ĐH Khoa Học Tự Nhiên",
    match: "92% Match",
    avatar: "LĐ",
    tags: ["Toán", "Tin học", "Quận 3, Quận 10", "Khớp lịch rảnh"],
    status: "Đang nhận lớp",
    highlight: "bg-green-600",
  },
  {
    id: "mock-tutor-4",
    rawTutorId: "mock-tutor-4",
    name: "Phan Ngọc Hà",
    meta: "3 năm kinh nghiệm · Cử nhân Sư phạm Toán",
    match: "90% Match",
    avatar: "PH",
    tags: ["Toán", "Ôn thi", "Bình Thạnh", "Khớp 2/2 buổi"],
    status: "Có thể dạy thử",
    highlight: "bg-green-600",
  },
]

export const mockStaffClasses: StaffClassItem[] = [
  {
    id: "mock-class-10293",
    code: "CLASS-10293",
    studentName: "Lê Trọng Tấn",
    tutorName: "Nguyễn Văn Bình",
    subject: "Toán học",
    location: "Quận 1, TP.HCM",
    feePerSession: "200.000",
    totalSessions: "24 buổi",
    status: "Đang học",
    startDate: "15/11/2023",
    endDate: "15/02/2024",
  },
  {
    id: "mock-class-10295",
    code: "CLASS-10295",
    studentName: "Trần Mỹ Duyên",
    tutorName: "Trần Thị Cẩm",
    subject: "Vật lý",
    location: "Quận 7, TP.HCM",
    feePerSession: "250.000",
    totalSessions: "20 buổi",
    status: "Hoàn thành",
    startDate: "01/10/2023",
    endDate: "20/12/2023",
  },
  {
    id: "mock-class-10297",
    code: "CLASS-10297",
    studentName: "Hoàng Gia Bảo",
    tutorName: "Phan Ngọc Hà",
    subject: "Hóa học",
    location: "Phú Nhuận, TP.HCM",
    feePerSession: "220.000",
    totalSessions: "18 buổi",
    status: "Tạm dừng",
    startDate: "22/11/2023",
    endDate: "22/01/2024",
  },
]
