import type { RequestItem, TutorRecommendation } from "@/types/class_request"

export const requests: RequestItem[] = [
  {
    id: "#RQ-10293",
    createdAt: "12/10/2023",
    name: "Lê Trọng Tấn",
    role: "Phụ huynh",
    phone: "0901 234 567",
    subject: "Toán học",
    level: "Lớp 10",
    area: "Quận 1, TP.HCM",
    schedule: "Tối Thứ 2, Thứ 4 · 19:00 - 21:00",
    note: "Ưu tiên gia sư ĐH Bách Khoa hoặc KHTN, có kinh nghiệm dạy kèm cấp 3.",
    status: "Chờ xử lý",
  },
  {
    id: "#RQ-10294",
    createdAt: "13/10/2023",
    name: "Ngô Minh An",
    role: "Học viên",
    phone: "0935 451 882",
    subject: "Tiếng Anh",
    level: "IELTS Foundation",
    area: "Thủ Đức, TP.HCM",
    schedule: "Sáng Thứ 7, Chủ nhật · 08:00 - 10:00",
    note: "Cần gia sư thiện về phát âm, giao tiếp, có giáo trình nền tảng phù hợp cho học viên mới.",
    status: "Đang xử lý",
  },
  {
    id: "#RQ-10295",
    createdAt: "13/10/2023",
    name: "Trần Mỹ Duyên",
    role: "Phụ huynh",
    phone: "0918 877 520",
    subject: "Vật lý",
    level: "Lớp 11",
    area: "Quận 7, TP.HCM",
    schedule: "Chiều Thứ 3, Thứ 5 · 17:30 - 19:30",
    note: "Ưu tiên gia sư có kinh nghiệm luyện học sinh khá giỏi, bổ trợ thêm bài tập nâng cao.",
    status: "Đã ghép",
  },
  {
    id: "#RQ-10296",
    createdAt: "14/10/2023",
    name: "Phạm Hữu Đức",
    role: "Học viên",
    phone: "0982 612 008",
    subject: "Ngữ văn",
    level: "Lớp 9",
    area: "Bình Thạnh, TP.HCM",
    schedule: "Tối Thứ 6, Chủ nhật · 18:30 - 20:00",
    note: "Cần gia sư theo sát kỹ năng viết đoạn văn nghị luận và củng cố phần đọc hiểu.",
    status: "Đang xử lý",
  },
  {
    id: "#RQ-10297",
    createdAt: "15/10/2023",
    name: "Hoàng Gia Bảo",
    role: "Phụ huynh",
    phone: "0907 225 114",
    subject: "Hóa học",
    level: "Lớp 12",
    area: "Phú Nhuận, TP.HCM",
    schedule: "Tối Thứ 3, Thứ 6 · 19:30 - 21:00",
    note: "Tập trung ôn thi tốt nghiệp, cần gia sư có lộ trình bài tập rõ ràng theo tuần.",
    status: "Chờ xử lý",
  },
]

export const tutors: TutorRecommendation[] = [
  {
    name: "Nguyễn Văn Bình",
    meta: "2 năm kinh nghiệm · Sinh viên ĐH Bách Khoa",
    match: "95% Match",
    avatar: "NV",
    tags: ["Toán", "Vật lý", "Quận 1, Quận 5", "Khớp 2/2 buổi"],
    status: "Hồ sơ đã duyệt",
    highlight: "bg-green-600",
  },
  {
    name: "Trần Thị Cẩm",
    meta: "5 năm kinh nghiệm · Giáo viên THPT",
    match: "85% Match",
    avatar: "TC",
    tags: ["Toán", "Hóa học", "Quận 1, Quận 4, Quận 7", "Khớp 1/2 buổi"],
    status: "Hồ sơ đã duyệt",
    highlight: "bg-orange-500",
  },
  {
    name: "Lê Minh Đạt",
    meta: "1.5 năm kinh nghiệm · ĐH Khoa Học Tự Nhiên",
    match: "92% Match",
    avatar: "LĐ",
    tags: ["Toán", "Tin học", "Quận 3, Quận 10", "Khớp lịch rảnh"],
    status: "Đang nhận lớp",
    highlight: "bg-green-600",
  },
  {
    name: "Phan Ngọc Hà",
    meta: "3 năm kinh nghiệm · Cử nhân Sư phạm Toán",
    match: "90% Match",
    avatar: "PH",
    tags: ["Toán", "Ôn thi", "Bình Thạnh", "Khớp 2/2 buổi"],
    status: "Có thể dạy thử",
    highlight: "bg-green-600",
  },
]
